### ISSUE TITLE
项目改个名？

### ISSUE THREAD

**Issue by hjiang** [leancloud/LCDB#1]
除了与老 API 相关的 API 仍然使用 AV 前缀外，其他任何地方都不要再以 AV 开头了。

**Comment by aisk** [comment]
http://www.avdb.im/

**Comment by tang3w** [comment]
@hjiang 我把源码的前缀也重新改了。

前缀 `AV` 与苹果的 `AVFoundation` 这个 framework 有冲突。我们 SDK 的前缀也是 `AV`。新引入的代码使用 `LC` 前缀如何？

@aisk 1024

**Comment by hjiang** [comment]
嗯，新的东西尽量 LC 前缀好了。

**Comment by wangxiao** [comment]
那 JS SDK 同时支持 AV（大写） 和 lc（小写），文档中全都暴露 lc，如何？

**Comment by hjiang** [comment]
@wangxiao JS 不是现在都主流用 `var lc = require('avoscloud');` 这样的写法吗？所以其实主要是包名吧？

**Comment by wangxiao** [comment]
对，这种形式主要是在 nodejs 里面，可以通过 require 模块化，浏览器中我们也支持的。但是浏览器环境中，还是要支持默认的直接加载即用的方式，需要一个默认的命名空间。

**Comment by aisk** [comment]
我们包名直接改成 `leancloud` 如何？
